apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocs-noobaa-only
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: gitops/manifests/content/workshop/ocs-noobaa-only/base
    repoURL: https://github.com/samueltauil/openshift-ml-workshop.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true