apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-serverless-subscription
  namespace: openshift-serverless
spec:
  channel: stable
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace